// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"609","screenHeight":"281","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Fullscreen","status":false,"description":"Starts the game in fullscreen","parameters":{}},
{"name":"BBS_VersionDisplay","status":true,"description":"v1.02 Adds display of the game version to the title screen.\nSpecial Thanks to Tsukihime for all the help.\nSpecial Thanks to 'Ramza' Michael Sweeney for all the support.\n\n============================================================================\nParameters\n============================================================================","parameters":{"Game Version Number":"0.0.8","Game Version Font":"","Version Font Size":"20","Show Version Number?":"true","Version Text Color":"white","Version Outline Color":"black","Version Outline Width":"8","Title Italic":"false","Version Text Max Width":"Graphics.width / 3"}},
{"name":"Galv_ScreenButtons","status":true,"description":"(v.1.3) Show buttons on screen that can be touched or clicked.","parameters":{"Precache Buttons":"BtnUp,BtnDown,BtnRight,BtnLeft,BtnOk,BtnCancel","Disable Mouse Move":"true","Button Fade":"30"}}
];
